services:
  - type: web
    name: gamecoach-app
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000  # Render kendi portunu override eder
      - key: TWILIO_SID
        sync: false
      - key: TWILIO_TOKEN
        sync: false
      - key: TWILIO_WHATSAPP_NUMBER
        sync: false
      - key: SHOPIER_SECRET
        sync: false
      - key: ADMIN_NUMBERS
        sync: false
